name: Release Rust Binaries

on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
        
          # Output target
          RUSTTARGET: ${{ matrix.target }}
          # List of archive types to publish the binaries with, default "zip", supports zip and all tar formats
          ARCHIVE_TYPES: ${{ matrix.archive }}
          # List of extra files to include in build
          EXTRA_FILES:  "README.md LICENSE"
